
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "phd.h"


static t_class *phd_class;

typedef struct _phd {
  t_object  x_obj;
} t_phd;

void phd_bang(t_phd *x)
{
  post("Hello world !!");
}

void *phd_new(void)
{
  printf("Calling new\n");
  t_phd *x = (t_phd *)pd_new(phd_class);

  return (void *)x;
}

void phd_setup(void) {
  printf("Calling setup\n");
  
  phd_class = class_new(gensym("phd"),
        (t_newmethod)phd_new,
        0, sizeof(t_phd),
        CLASS_DEFAULT, A_NULL);
  class_addbang(phd_class, phd_bang);
}



